In [1]:
# Let's import the needed packages
import pandas as pd
import requests
import json

In [26]:
# Let's download the json data from the forbes website
url = 'https://www.forbes.com/billionaires/page-data/index/page-data.json'
r = requests.get(url)

In [ ]:
# Let's save the data as json file
with open('forbes_billionaires.json','w',encoding='utf') as f:
        json.dump(r.json(), f, ensure_ascii=False, indent=4)

In [31]:
# # Let's get the data from the json without
file_path = './forbes_billionaires.json'
with open(file_path, 'r') as f:
    #load json data from file
    data = json.load(f)
extracted_data = data['result']['pageContext']['tableData']

In [33]:
data['result']['pageContext']['tableData'][0]

{'name': 'Billionaires',
 'year': 2022,
 'month': 4,
 'uri': 'elon-musk',
 'rank': 1,
 'listUri': 'billionaires',
 'finalWorth': 219000,
 'category': 'Automotive',
 'otherCompensation': 0,
 'person': {'name': 'Elon Musk',
  'uri': 'elon-musk',
  'imageExists': True,
  'squareImage': 'https://specials-images.forbesimg.com/imageserve/62d700cd6094d2c180f269b9/416x416.jpg?background=000000&cropX1=0&cropX2=959&cropY1=0&cropY2=959'},
 'visible': True,
 'personName': 'Elon Musk',
 'age': 50,
 'country': 'United States',
 'state': 'Texas',
 'city': 'Austin',
 'source': 'Tesla, SpaceX',
 'industries': 'Automotive',
 'countryOfCitizenship': 'United States',
 'organization': 'Tesla',
 'timestamp': 1664284092360,
 'version': 1,
 'naturalId': 'faris/5/2022/14117',
 'position': 1,
 'imageExists': True,
 'selfMade': True,
 'status': 'U',
 'gender': 'M',
 'birthDate': 46915200000,
 'lastName': 'Musk',
 'firstName': 'Elon',
 'listDescription': "The World's Billionaires",
 'title': 'CEO',
 'employment': {'name': 'Tesla',
  'uri': 'companies/tesla',
  'title': 'CEO',
  'government': False},
 'date': 1649134860000,
 'wealthList': False,
 'familyList': False,
 'selfMadeRank': 8,
 'thumbnail': 'http://specials-images.forbesimg.com/imageserve/62d700cd6094d2c180f269b9/280x425.jpg?fit=scale&background=000000',
 'residenceStateRegion': 'South',
 'squareImage': 'https://specials-images.forbesimg.com/imageserve/62d700cd6094d2c180f269b9/416x416.jpg?background=000000&cropX1=0&cropX2=959&cropY1=0&cropY2=959',
 'bioSuppress': False,
 'csfDisplayFields': ['rank', 'finalWorth', 'personName', 'bios', 'bio'],
 'suppressOnProfiles': False,
 'qas': [{'question': 'Innovative Leaders: 12-month Sales Growth, %',
   'answer': '27.03',
   'hidden': False},
  {'question': 'Innovative Leaders: Company Innovation Premium',
   'answer': '72.16',
   'hidden': False}],
 'bios': ['Elon Musk cofounded six companies including electric car maker Tesla, rocket producer SpaceX and tunneling startup Boring Company.',
  'He owns about 25% of Tesla between stock and options, but has pledged more than half his stock as collateral for loans.',
  'SpaceX, founded in 2002, is worth $127 billion after a funding round in May 2022; it quadrupled its value in three years.',
  'Boring Company, which aims to defeat traffic, raised $675 million in April 2022 at a $5.7 billion valuation.',
  "Twitter's board agreed to sell the company to Musk for $44 billion in April 2022, after he disclosed a 9.1% stake and threatened a hostile takeover.",
  'In July 2022, Musk announced he was terminating the deal over bot concerns. Twitter sued and the parties will go to court in October.'],
 'abouts': ["Musk, who says he's worried about population collapse, has nine children with three women including triplets and two sets of twins.",
  'As a kid in South Africa, Musk taught himself to code; he sold his first game, Blastar, for about $500.'],
 'premiumProfile': False,
 'philanthropyScore': 1,
 'embargo': False,
 'netWorth': '$219 B'}

In [32]:
def get_item(item, name):
    try: 
        item_name = item[name]
    except:
        item_name = ''
    return item_name

In [37]:
# Let's get the data from the extracted data
billionaires = []
for i,item in enumerate(extracted_data):
    rank = get_item(item, 'rank')
    name = get_item(item, 'personName')
    age = get_item(item, 'age')
    country = get_item(item, 'country')
    net_worth = get_item(item, 'netWorth')
    category = get_item(item, 'category')
    source = get_item(item, 'source')
    image = get_item(item, 'squareImage')
    birthDate = get_item(item, 'birthDate')
    gender = get_item(item, 'gender')
    organization = get_item(item, 'organization')
    title = get_item(item, 'title')
    philanthropyScore = get_item(item, 'philanthropyScore')
    selfMade = get_item(item, 'selfMade')
    billionaires.append([rank,name,age,country,net_worth,category,source,image,birthDate,gender,organization,title,philanthropyScore,selfMade])

In [38]:
billionaires_data = pd.DataFrame(
    billionaires,
    columns=['rank','person_name','age','country','net_worth(billion $)','category','source','image_url','birth_date','gender','organization','title','philanthropy_score','self_made']
    )

In [39]:
billionaires_data

,rank,person_name,age,country,net_worth(billion $),category,source,image_url,birth_date,gender,organization,title,philanthropy_score,self_made
0,1,Elon Musk,50,United States,$219 B,Automotive,"Tesla, SpaceX",https://specials-images.forbesimg.com/imageser...,46915200000,M,Tesla,CEO,1,True
1,2,Jeff Bezos,58,United States,$171 B,Technology,Amazon,https://specials-images.forbesimg.com/imageser...,-188438400000,M,Amazon,Chairman and Founder,1,True
2,3,Bernard Arnault & family,73,France,$158 B,Fashion & Retail,LVMH,//specials-images.forbesimg.com/imageserve/5dc...,-657244800000,M,LVMH Moët Hennessy Louis Vuitton,Chairman and CEO,N/A,False
3,4,Bill Gates,66,United States,$129 B,Technology,Microsoft,https://specials-images.forbesimg.com/imageser...,-447465600000,M,Bill & Melinda Gates Foundation,Cofounder,4,True
4,5,Warren Buffett,91,United States,$118 B,Finance & Investments,Berkshire Hathaway,//specials-images.forbesimg.com/imageserve/5ba...,-1241481600000,M,Berkshire Hathaway Inc. (Cl A),CEO,5,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2663,2578,Zhang Yuqiang,66,China,$1 B,Manufacturing,Fiberglass,,-452390400000,M,,,N/A,True
2664,2578,Zhou Ruxin,59,China,$1 B,Technology,Navigation,,-215827200000,M,,,N/A,True
2665,2578,Wen Zhou & family,57,China,$1 B,Manufacturing,chemicals,,-152236800000,M,,,N/A,True
2666,2578,Zhou Yifeng & family,43,China,$1 B,Energy,liquefied petroleum gas,,268963200000,F,,,N/A,True
2667,2578,Zhuang Kuilong & family,59,China,$1 B,Manufacturing,polyester,,-238204800000,M,,,N/A,True

In [ ]:
url_for_missing_profile_image = 'https://img.freepik.com/premium-vector/man-avatar-profile-picture-vector-illustration_268834-541.jpg?size=338&ext=jpg&ga=GA1.1.1546980028.1704412800&semt=ais'

In [40]:
# Saving the data in a csv file in our datasets folder
billionaires_data.to_csv('datasets/billionaires_data_2022.csv',index=False)

In [ ]:
# Saving the data to an excel file
billionaires_data.to_excel('datasets/billionaires_data_2022.xlsx',index=False)